### ISSUE TITLE
Running into an issues on running example.py

### ISSUE THREAD

**Issue by korymath** [ludc/rltorch#4]
$ python example.py 
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    import lutorpy as lua
  File "/Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg/lutorpy/__init__.py", line 72, in <module>
    LuaRuntime()
  File "/Users/kmathewson/anaconda/envs/rllab/lib/python2.7/site-packages/lutorpy-1.3-py2.7-macosx-10.5-x86_64.egg/lutorpy/__init__.py", line 69, in LuaRuntime
    luaRuntime = lutorpy._lupa.LuaRuntime(*args, **kwargs)
  File "lutorpy/_lupa.pyx", line 231, in lutorpy._lupa.LuaRuntime.__cinit__ (lutorpy/_lupa.c:4642)
lutorpy._lupa.LuaError: Failed to initialise Lua runtime

**Comment by korymath** [comment]
Trying to get lutorpy running nicely.

**Comment by ludc** [comment]
Hi,

Sorry, I have no experience about lutorpy  on macos. Perhaps this issue could be posted on the lutorpy website or the lupa one since lutorpy is based on lupa.

Have a look at, maybe it could help:
* https://github.com/scoder/lupa/issues/13
* https://github.com/scoder/lupa/issues/23

**Comment by korymath** [comment]
Thanks for the quick reply; will follow up.
